ALTER TABLE "site_settings"
  ADD COLUMN IF NOT EXISTS "smtp_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "smtp_host" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_port" INTEGER,
  ADD COLUMN IF NOT EXISTS "smtp_secure" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "smtp_user" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_password" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_from_name" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_from_email" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_reply_to" TEXT,
  ADD COLUMN IF NOT EXISTS "smtp_batch_size" INTEGER NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS "smtp_batch_delay_ms" INTEGER NOT NULL DEFAULT 1500;
