export const endpoints = {
  health: () => '/health',
  auth: {
    login: () => '/auth/login',
    refresh: () => '/auth/refresh',
    logout: () => '/auth/logout',
    me: () => '/auth/me',
  },
  audit: {
    list: () => '/audit',
  },
  notifications: {
    list: () => '/notifications',
    send: () => '/notifications',
    sendList: () => '/notifications/send-list',
  },
  users: {
    list: () => '/users',
    create: () => '/users',
    updateMe: () => '/users/me',
    changePassword: () => '/users/me/password',
    detail: (id: string) => `/users/${id}`,
    resetPassword: (id: string) => `/users/${id}/reset-password`,
  },
  venues: {
    list: () => '/venues',
    create: () => '/venues',
    detail: (id: string) => `/venues/${id}`,
  },
  events: {
    list: () => '/events',
    create: () => '/events',
    detail: (id: string) => `/events/${id}`,
    responsibles: (eventId: string) => `/events/${eventId}/responsibles`,
    attendance: (eventId: string) => `/events/${eventId}/attendance`,
    attendanceStats: (eventId: string) => `/events/${eventId}/attendance/stats`,
    preregisterAttendance: (eventId: string) => `/events/${eventId}/attendance/preregister`,
    scanAttendance: (eventId: string) => `/events/${eventId}/attendance/scan`,
  },
  attendance: {
    qr: (attendanceId: string) => `/attendance/${attendanceId}/qr`,
    certificate: (attendanceId: string) => `/attendance/${attendanceId}/certificate`,
    detail: (attendanceId: string) => `/attendance/${attendanceId}`,
  },
  public: {
    settings: () => '/public/settings',
    events: () => '/public/events',
    tournaments: () => '/public/tournaments',
    eventForm: (eventId: string) => `/public/events/${eventId}/form`,
    eventFormQr: (eventId: string) => `/public/events/${eventId}/form-qr.svg`,
    eventRegister: (eventId: string) => `/public/events/${eventId}/register`,
    eventCheckIn: (eventId: string) => `/public/events/${eventId}/check-in`,
    tournamentForm: (tournamentId: string) => `/public/tournaments/${tournamentId}/form`,
    tournamentFormQr: (tournamentId: string) => `/public/tournaments/${tournamentId}/form-qr.svg`,
    tournamentRegister: (tournamentId: string) => `/public/tournaments/${tournamentId}/register`,
  },
  settings: {
    detail: () => '/settings',
  },
  speakers: {
    list: () => '/speakers',
    create: () => '/speakers',
    detail: (id: string) => `/speakers/${id}`,
  },
  talks: {
    list: () => '/talks',
    create: () => '/talks',
    detail: (id: string) => `/talks/${id}`,
  },
  tournaments: {
    list: () => '/tournaments',
    create: () => '/tournaments',
    detail: (id: string) => `/tournaments/${id}`,
    registrations: (id: string) => `/tournaments/${id}/registrations`,
    fixture: (id: string) => `/tournaments/${id}/fixture`,
    standings: (id: string) => `/tournaments/${id}/standings`,
    recalculateStandings: (id: string) => `/tournaments/${id}/standings/recalculate`,
    standingDetail: (id: string, standingId: string) => `/tournaments/${id}/standings/${standingId}`,
    exportExcel: (id: string) => `/tournaments/${id}/export.xlsx`,
    generateGroups: (id: string) => `/tournaments/${id}/groups/generate`,
    generateFixture: (id: string) => `/tournaments/${id}/fixture/generate`,
    matches: (id: string) => `/tournaments/${id}/matches`,
    matchDetail: (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}`,
    matchScore: (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}/score`,
    matchClose: (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}/close`,
    teams: (id: string) => `/tournaments/${id}/teams`,
    teamDetail: (id: string, teamId: string) => `/tournaments/${id}/teams/${teamId}`,
    participants: (id: string) => `/tournaments/${id}/participants`,
    participantDetail: (id: string, participantId: string) =>
      `/tournaments/${id}/participants/${participantId}`,
  },
  hackathon: {
    list: () => '/hackathon',
    create: () => '/hackathon',
    detail: (id: string) => `/hackathon/${id}`,
    overview: (id: string) => `/hackathon/${id}/overview`,
    companies: () => '/hackathon/companies',
    companyDetail: (companyId: string) => `/hackathon/companies/${companyId}`,
    challenges: (id: string) => `/hackathon/${id}/challenges`,
    challengeDetail: (challengeId: string) => `/hackathon/challenges/${challengeId}`,
    teams: (id: string) => `/hackathon/${id}/teams`,
    teamDetail: (id: string, teamId: string) => `/hackathon/${id}/teams/${teamId}`,
    deliverables: (id: string, teamId: string) => `/hackathon/${id}/teams/${teamId}/deliverables`,
    deliverableDetail: (id: string, teamId: string, deliverableId: string) =>
      `/hackathon/${id}/teams/${teamId}/deliverables/${deliverableId}`,
  },
};
